### ISSUE TITLE
Scores are incorrect or not completed

### ISSUE THREAD

**Issue by johnpiers** [acifani/soccer-go#362]
First off I'd just like to say that I absolutely love this thing. 

Of late there seems to be a problem with the final scores, they are not reflecting correctly after the game has finished. The World Cup feed seems to be the biggest culprit. 

Thanks.

![soccer-go](https://user-images.githubusercontent.com/1306639/205432447-e3b58415-2bf1-411d-a10b-f16acaed27aa.jpg)

**Comment by johnpiers** [comment]
Seems to be corrected since the last update. Thanks.

**Comment by acifani** [comment]
Hey @johnpiers, thanks for the update! Let me know if you run into any issues and thanks for the kind words ❤️
