### ISSUE TITLE
archlinux aur nodejs-soccer-go 0.4.0-2

### ISSUE THREAD

**Issue by cirrusUK** [acifani/soccer-go#42]
## Expected Behavior

as shown in README.md
## Actual Behavior
all commands =
✖ Fetching competition...
✖ Fetching matchday...
undefined
410

## Steps to Reproduce the Problem

  1. install nodejs-soccer-go 0.4.0-2 from [aur ](https://aur.archlinux.org/packages/nodejs-soccer-go/)on fully updated Archlinux box
  2.  execute any soccer-go command
 

## Specifications

- Version: 0.4.0-2
- Platform:  Archlinux
- NodeJS Version: [community/nodejs](https://www.archlinux.org/packages/community/x86_64/nodejs/) 11.6.0-1 [installed]

Is this a problem with the AUR pkg maintainer, should i flag his pkg out of date or is the problem from upstream?
Regards & thanks for the code :xd

**Comment by matt-block** [comment]
Have you tried installing it globally via NPM, just to see if it's the AUR package the one with issues or both?

In any case, tomorrow I'll investigate a bit on this.

**Comment by cirrusUK** [comment]
i get errors usiing both  methods
`cirrus@hawker64  /home/cirrus   node /usr/lib/node_modules/soccer-go/lib/cache/index.js                                                     21:25:05 
fs.js:121
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/soccer-go/lib/cache/.cache'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at new Cache (/usr/lib/node_modules/soccer-go/lib/cache/Cache.js:35:20)
    at Object.<anonymous> (/usr/lib/node_modules/soccer-go/lib/cache/index.js:13:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
`

**Comment by matt-block** [comment]
I had a quick look and the "issue" is in the API: we are using v1 which was rendered obsolete at the beginning of the year.

We need to migrate to v2 to solve this. I can work on this but only over the weekend.

@tytondon1234 
@cirrusUK (sorry for the late response)

**Comment by acifani** [comment]
@cirrusUK @tytondon1234 Hi guys, apologize for being so late to the party. Our [data provider](https://www.football-data.org/) has recently deprecated the APIs we were using, as @matt-block noticed.

The V2 will also have a stricter free tier and require an API key to work. I can see 2 options going forward:

1. Move to a client/server model, with me providing the API key on the server
2. Make users provide their own API key. This will be a bit inconvenient but also will guarantee not running into the free tier capping that a shared API key will probably cause

**Comment by acifani** [comment]
@cirrusUK @tytondon1234 Hi guys, I've published version 0.5.0 on [npm](https://www.npmjs.com/package/soccer-go). AUR should follow soon, I'm in contact with the guy and I'll tell him to update his version. 

I've decided to go with option 2 for now, meaning everyone has to provide its own API key and set it to `SOCCER_GO_API_KEY` env var. You can get it here: https://www.football-data.org/client/register

Feedback is welcome

**Comment by cirrusUK** [comment]
@acifani Im glad to report that its seems to be the AUR pkg at fault. it throws same permissions error even after exporting new API key, however installing with npm it works great, thanks for the code and apoligies for my belated response.
regards
