### ISSUE TITLE
Issue with line endings

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [acifani/soccer-go#43]
## Expected Behavior
Execute the CLI on macOS and maybe linux

## Actual Behavior
prints out `env: node\r: No such file or directory`

## Steps to Reproduce the Problem

  1. `npm i -g soccer-go`
  2. `soccer-go`

## Specifications

- Version: 0.4.2
- Platform: macOS 10.13.6
- NodeJS Version: 8.9.0

**Comment by acifani** [comment]
Hey there @tiagomsmagalhaes, I know it's been quite a while, but I've published v0.5.0 which should fix a lot of issues we were having. Let me know if it fixes the error for you

**Comment by tiagomsmagalhaes** [comment]
It's fixed. Thanks
